name: NodeJS Github Actions 

on: 
  push:
    branches: 
      - main
      - develop
      - staging
      - Pre-production
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      
      - name: setup node 
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies 
        run: npm install 
     

  test: 
    steps:
      - name: Run test 
        run: npm test
